"""create users table

Revision ID: 1809cbc82dfa
Revises: 
Create Date: 2026-01-22 00:37:55.568669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1809cbc82dfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('devices',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('TUYA', 'SNMP', name='devicetype'), nullable=False),
    sa.Column('icon', sa.Enum('PLUG', 'MONITOR', 'TV', 'AIR_VENT', 'PRINTER', 'SERVER', 'ROUTER', 'LIGHTBULB', 'CAMERA', 'COFFEE', 'FAN', 'SPEAKER', 'REFRIGERATOR', name='deviceicon'), nullable=False),
    sa.Column('is_on', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', name='devicestatus'), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('local_key', sa.String(length=255), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('community_string', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('snmp_base_oid', sa.String(length=255), nullable=True),
    sa.Column('snmp_outlet_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=True)
    op.create_index(op.f('ix_devices_status'), 'devices', ['status'], unique=False)
    op.create_index(op.f('ix_devices_type'), 'devices', ['type'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('routines',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trigger_type', sa.Enum('TIME', 'MANUAL', 'ROUTINE_COMPLETE', 'DEVICE_STATE', name='triggertype'), nullable=False),
    sa.Column('trigger_time', sa.Time(), nullable=True),
    sa.Column('week_days', postgresql.ARRAY(sa.Enum('SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB', 'DOM', name='weekday')), nullable=False),
    sa.Column('trigger_routine_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('trigger_device_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('trigger_device_state', sa.Enum('ON', 'OFF', name='triggerdevicestate'), nullable=True),
    sa.Column('trigger_cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trigger_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trigger_routine_id'], ['routines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routines_id'), 'routines', ['id'], unique=True)
    op.create_index(op.f('ix_routines_is_active'), 'routines', ['is_active'], unique=False)
    op.create_index(op.f('ix_routines_trigger_device_id'), 'routines', ['trigger_device_id'], unique=False)
    op.create_index(op.f('ix_routines_trigger_routine_id'), 'routines', ['trigger_routine_id'], unique=False)
    op.create_index(op.f('ix_routines_trigger_type'), 'routines', ['trigger_type'], unique=False)
    op.create_index(op.f('ix_routines_user_id'), 'routines', ['user_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.Enum('DEVICE_ON', 'DEVICE_OFF', 'DEVICE_ADDED', 'DEVICE_UPDATED', 'DEVICE_DELETED', 'ROUTINE_ACTIVATED', 'ROUTINE_DEACTIVATED', 'ROUTINE_CREATED', 'ROUTINE_UPDATED', 'ROUTINE_DELETED', 'ROUTINE_EXECUTED', 'MASTER_SWITCH', name='activitytype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('device_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('routine_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('routine_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_device_id'), 'activity_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=True)
    op.create_index(op.f('ix_activity_logs_routine_id'), 'activity_logs', ['routine_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_type'), 'activity_logs', ['type'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('routine_actions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('routine_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('device_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('turn_on', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_actions_device_id'), 'routine_actions', ['device_id'], unique=False)
    op.create_index(op.f('ix_routine_actions_id'), 'routine_actions', ['id'], unique=True)
    op.create_index(op.f('ix_routine_actions_routine_id'), 'routine_actions', ['routine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routine_actions_routine_id'), table_name='routine_actions')
    op.drop_index(op.f('ix_routine_actions_id'), table_name='routine_actions')
    op.drop_index(op.f('ix_routine_actions_device_id'), table_name='routine_actions')
    op.drop_table('routine_actions')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_routine_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_device_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_routines_user_id'), table_name='routines')
    op.drop_index(op.f('ix_routines_trigger_type'), table_name='routines')
    op.drop_index(op.f('ix_routines_trigger_routine_id'), table_name='routines')
    op.drop_index(op.f('ix_routines_trigger_device_id'), table_name='routines')
    op.drop_index(op.f('ix_routines_is_active'), table_name='routines')
    op.drop_index(op.f('ix_routines_id'), table_name='routines')
    op.drop_table('routines')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_type'), table_name='devices')
    op.drop_index(op.f('ix_devices_status'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
